forms.py
# forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired


"""
 class form that defines what the form is made of
 particularly
"""
class RecipeEditForm(FlaskForm):
    title = StringField(
        'Title', validators=[DataRequired()]
    )

    ingridient = TextAreaField(
        'Ingridient', validators=[DataRequired()]
    )

    desc = TextAreaField(
        'Desc', validators=[DataRequired()]
    )

views.py
# views.py
#third party import
from flask import Blueprint, render_template, current_app, request, redirect, url_for

main = Blueprint('main', __name__)


#local import
from recipe import Recipe
from forms import RecipeEditForm
#from initial import main


@main.route('/')
@main.route('/index')
def index():
    return render_template('index.html')

@main.route('/login')
def login():
    return render_template('login.html')

@main.route('/recipes', methods=['GET', 'POST'])
def recipes_page():
    if request.method == 'GET':
        recipes = current_app.recipeCrud.get_recipes()
        return render_template('recipes.html', recipes=sorted(recipes.items()))
    else:
        recipe_ids = request.form.getlist('recipe_ids')
        for recipe_id in recipe_ids:
            current_app.recipeCrud.delete_recipe(int(recipe_id))
        return redirect(url_for('main.recipes_page'))

@main.route('/recipe/<int:recipe_id>')
def recipe_page(recipe_id):
    recipe = current_app.recipeCrud.get_recipe(recipe_id)
    return render_template('recipe.html', recipe=recipe)

@main.route('/recipes/add', methods=['GET', 'POST'])
def recipe_add_page():
    form = RecipeEditForm()
    if form.validate_on_submit():
        title = form.data['title']
        ingridient = form.data['ingridient']
        desc = form.data['desc']

        recipe = Recipe(title, ingridient, desc)

        current_app.recipeCrud.add_recipe(recipe)
        return redirect(url_for('main.recipe_page', recipe_id=recipe._id))
    return render_template('recipe_edit.html', form=form)

@main.route('/recipe/<int:recipe_id>/edit', methods=['GET', 'POST'])
def recipe_edit_page(recipe_id):
    recipe = current_app.recipeCrud.get_recipe(recipe_id)
    form = RecipeEditForm()
    if form.validate_on_submit():
        recipe.title = form.data['title']
        recipe.ingridient = form.data['ingridient']
        recipe.desc = form.data['desc']

        current_app.recipeCrud.update_recipe(recipe)
        return redirect(url_for('main.recipe_page', recipe_id=recipe._id))
    form.title.data = recipe.title
    form.ingridient.data = recipe.ingridient
    form.desc.data = recipe.desc
    return render_template('recipe_edit.html', form=form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    
    <title>Yummy Recipes - {% block title %}{% endblock %}</title>

    <link href="{{url_for('static', filename='styles/normalize.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{url_for('static', filename='bootstrap/css/bootstrap-responsive.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{url_for('static', filename='styles/custom.css')}}" rel="stylesheet">
</head>

<body>
    <div class="container">
        <nav class="navbar mg-b=5">
            <div class="container">
                <div class="navbar-header">
                        <div class="row-fluid margin-top">
                            <div class="span2"><a href="#" class="btn">Home</a></div>
                            <div class="span2"><a href="{{url_for('main.recipes_page')}}" class="btn">View Public Recipes</a></div>
                            <div class="span2"><a href="{{url_for('main.recipe_add_page')}}" class="btn">Add a Recipe</a></div>
                            <div class="span2 offset4"><a href="{{url_for('main.login')}}" class="btn bold">Sign In</a></div>
                        </div> 
                </div>
            </div>
        </nav>
    </div>
    <div class="container" role="main">
        {% block content %}{% endblock %} 
    </div>

   <footer>
       &copy; 2017, Emmisteel
   </footer>

   <script src="{{url_for('static', filename='bootstrap/js/jquery-latest.js')}}"></script>
   
   <!--include all compiled plugins-->
   <script src="{{url_for('static', filename='bootstrap/js/bootstrap.min.js')}}"></script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
    <div class="page-header">
            <div class="row-fluid">
                <div class="span8 offset2 bg-white title-style ">
                    <h1>Yummy Recipes</h1>
                </div>
            </div>
            <div class="row-fluid">
                    <div class="">
                        <h3>Create Account</h3>
                    </div>
                </div>
    </div>
    <div class="offset2 span9 centre-table margin-3em row-fliud">
            <table class="two-cln">
                <tr><td class="left-align bold">FULL NAME:</td> <td><input type="text" class="span5" name="fullname"></td></tr>
                
                <tr><td class="left-align bold">EMAIL:</td> <td><input type="email" class="span5" name="fullname"></td></tr>
          
                <tr><td class="left-align bold">PASSWORD:</td> <td><input type="password" name="password" class="span5" /></td></tr>
                
                <tr><td class="left-align bold">CONFIRM PASSWORD:</td> <td><input type="password" name="password" class="span5" /></td></tr>
                
                
            </table>
        </div>
        
        <div class="row-fluid offset6 span2">
            <input type="submit" name="submit" value="SIGN UP" class="btn span2 bold color"/>
        </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
    <div class="page-header">
            <div class="row-fluid">
                <div class="span8 offset2 bg-white title-style ">
                    <h1>Yummy Recipes</h1>
                </div>
            </div>
            <div class="row-fluid">
                    <div class="">
                        <h3>Sign In</h3>
                    </div>
                </div>
    </div>
    <form action="{{url_for('main.addrecipe')}}" method="POST">
            <div class="offset2 span9 centre-table margin-3em row-fliud">
        
                <table class="two-cln">
                    <tr>
                         <td class="left-align bold">EMAIL</td> <td><input type="email" class="span5"></td>
                    </tr>
                    
                    <tr>
                        <td class="left-align bold">PASSWORD</td> <td><input type="password" name="password" class="span5" /></td>
                        
                    </tr>
                </table>
            </div>
            
            <div class="row-fluid offset6 span2">
                <input type="submit" name="submit" value="LOGIN" class="btn span2 bold color"/>
            </div>
         </form>
{% endblock %}

templates/recipe.html
{% extends 'base.html' %}

{% block title %}Recipe{% endblock %}

{% block content %}
    <div class="page-header" style="margin-bottom: 20px">
        <h2>{{recipe.title}}</h2>
    </div>

    <div class="row">
        <div class="col-sm-2">Ingridients</div>
        <div class="col-sm-10">{{recipe.ingridient}}</div>
    </div>

    
    <div class="row">
        <div class="col-sm-2">Description</div>
        <div class="col-sm-10">{{recipe.desc}}</div>
    </div>

    <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-10">
                <a href="{{ request.path }}/edit" class="btn btn-primary">Edit</a>
            </div>
        </div>

{% endblock %}

templates/recipe_edit.html
{% extends "base.html" %}
{% block title %}Edit Recipe{% endblock %}
{% block content %}
<div class="page-header">
        <h1>Edit Recipe</h1>
      </div>

      <form role="form" action="" method="post" name="recipe_edit"
            class="form-horizontal">

            {{form.csrf_token }}

        <div class="form-group">
          <label for="title" class="control-label col-sm-2">Title:</label>
          <div class="col-sm-10">
            {{ form.title(required=True, autofocus=True) }}
              {% for error in form.title.errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
              {% endfor %}
          </div>
        </div>

        <div class="form-group">
          <label for="year" class="control-label col-sm-2">Ingridient:</label>
          <div class="col-sm-10">
              {{ form.ingridient(required=True, autofocus=True) }}
              {% for error in form.ingridient.errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
              {% endfor %}
          </div>
        </div>

        <div class="form-group">
                <label for="year" class="control-label col-sm-2">Description:</label>
                <div class="col-sm-10">
                    {{ form.desc(required=True, autofocus=True) }}
                    {% for error in form.desc.errors %}
                          <div class="alert alert-danger">
                              {{ error }}
                          </div>
                    {% endfor %}
                </div>
              </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" name="save"
                    class="btn btn-primary">Save</button>
          </div>
        </div>
</form>
{% endblock %}

templates/recipes.html
{% extends 'base.html' %}

{% block title %}Recipe List{% endblock %}

{% block content %}
<div class='page-header'>
    <h2>Recipes</h2>
  </div>
  
  
    {% if recipes %}
    <form role="form" action="" method="post" name="recipes" class="form-vertical">

    <ul class="list-unstyled">
      {% for recipe_id, recipe in recipes %}
          <li>
            <input type="checkbox" name="recipe_ids" value="{{recipe_id}}" />
            <a href="{{ url_for('main.recipe_page', recipe_id=recipe_id) }}">
            {{ recipe.title }}
            {{ recipe.ingridient }}
            {{ recipe.desc}}
          </a>
          </li>
        
      {% endfor %}  
    </ul>
    <button type="submit" name="delete" class="btn btn-primary">Delete</button>
    </form>
    {% endif %}
{% endblock %}